#+TITLE: Labsheet

* Tasks
** Money
Write a function named money that accepts
- a single integer parameter that represents a total number of cents,
and breaks the total down into its numbers of dollars and cents.

Your function should calculate the number of:
- dollars, and
- the number of "left-over" cents, and
- provide these to its calling function through its parameters.

For example, a value of 524 should be "returned" as 5 dollars and 24 cents.

Your function should have the prototype:
#+BEGIN_SRC C
void money(int total, int *dollars, int *cents);
#+END_SRC

and called as:
#+BEGIN_SRC
money(524, &dollars, &cents);
#+END_SRC
** str functions
1. strcat
2. strcmp
3. strncmp
4. strchr
5. strrchr
6. strpbrk
7. strstr

Maintain two separate C source files for this task:
- one file for the array-based versions of each function (named arrays.c),
- and one file for the pointer-based versions (named pointers.c).

Develop two separate header files:
- one containing the prototypes of the array-based functions (named arrays.h),
- and the other containing the prototypes of the pointer-based functions (named pointers.h).

Create a single testing program named stringtest.c.
- It should contain the only main() function for this question,
- It tests each of the functions you write.
- The file stringtest.c should include both of your header files.
